# Generated by Django 4.2.3 on 2023-07-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'one'), ('Female', 'two'), ('others', 'three')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'one'), ('others', 'five'), ('Christian', 'three'), ('Bouddho', 'four'), ('Hindu', 'two')], max_length=10, null=True),
        ),
    ]
