# Generated by Django 4.2.3 on 2023-07-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0002_alter_profile_gender_alter_profile_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('Muslim', 'one'), ('Hindu', 'two'), ('Christian', 'three'), ('Bouddho', 'four'), ('others', 'five')], max_length=10, null=True),
        ),
    ]
