# Generated by Django 4.2.3 on 2023-07-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruds', '0003_alter_profile_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('one', 'Male'), ('two', 'Female'), ('three', 'others')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(blank=True, choices=[('one', 'Muslim'), ('two', 'Hindu'), ('three', 'Christian'), ('four', 'Bouddho'), ('five', 'others')], max_length=10, null=True),
        ),
    ]
